
include:
  - georchestra/geor-compose.yml
  - georchestra/geor-compose.override.yml

services:
  maelstro-back:
    build: ./backend
    volumes:
      - ./backend:/app
    healthcheck:
      test: "poetry run health_check"
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

    ports:
      - 8000:8000

    command:
      - poetry
      - run
      - docker_dev
