
include:
  - georchestra/geor-compose.yml
  - georchestra/geor-compose.override.yml

services:
  maelstro-front:
    build:
      context: ./frontend
      target: server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

  maelstro-back:
    build:
      context: ./backend
      target: server
    volumes:
      - ./backend:/app
    healthcheck:
      test: "health_check"
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

    command:
      - serve_docker_dev

  check:
    profiles:
      - check
    build:
      context: ./backend
      target: check
    volumes:
      - ./backend:/app
