
volumes:
    postgresql_data:

services:
  database:
    image: postgres:16
    env_file:
      - .envs-database
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: no

  maelstro-front:
    build:
      context: ./frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/maelstro/"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    volumes:
      - ./config/:/etc/maelstro/:ro
    environment:
      MAELSTRO_BACK_HOST: maelstro-back
    ports:
      - "8080:8080"

  maelstro-back:
    build:
      context: ./backend
      target: server
    healthcheck:
      test: "health_check"
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    volumes:
      - ./backend:/app
      - ./config/:/etc/maelstro/:ro
    env_file:
      - .envs-database
    environment:
      MAELSTRO_CONFIG: /etc/maelstro/config.yaml
      LOCAL_LOGIN: "testadmin"
      LOCAL_PASSWORD: "testadmin"
      DEMO_CRD: "test12"
    command:
      - serve_docker_dev

  check:
    profiles:
      - check
    build:
      context: ./backend
      target: check
    environment:
      MAELSTRO_CONFIG: /app/tests/test_config.yaml
      LOCAL_LOGIN: testadmin
      LOCAL_PASSWORD: testadmin
    volumes:
      - ./backend:/app