
services:
  maelstro-front:
    build:
      context: ./frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/maelstro/"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    volumes:
      - ./config/:/etc/maelstro/:ro
      - ./config/nginx-solo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:8080"
    environment:
      CUSTOM_SCRIPTS_DIRECTORY: /etc/maelstro/scripts

  maelstro-back:
    build:
      context: ./backend
      target: server
    volumes:
      - ./config/:/etc/maelstro/:ro
    environment:
      MAELSTRO_CONFIG: /etc/maelstro/config.yaml
      LOCAL_LOGIN: testadmin
      LOCAL_PASSWORD: testadmin
    healthcheck:
      test: "health_check"
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    command:
      - serve_docker_dev


