sources:
  login: testadmin
  password: testadmin
  geonetwork_instances:
    - name: "GeonetworkMaster"
      api_url: https://demo.georchestra.org/geonetwork/srv/api
  geoserver_instances:
    - url: "https://demo.georchestra.org/geoserver"

destinations:
  "CompoLocale":
    login_env_var: LOCAL_LOGIN
    password_env_var: LOCAL_PASSWORD
    geonetwork:
      api_url: http://proxy:8080/geonetwork/srv/api
    geoserver:
      url: http://proxy:8080/geoserver
