apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-maelstro.fullname" . }}-maelstro-frontend-svc
  labels:
    {{- include "helm-maelstro.labels" . | nindent 4 }}
spec:
  type: {{ .Values.maelstro_frontend.service.type }}
  ports:
    - port: {{ .Values.maelstro_frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
     app.kubernetes.io/name: {{ include "helm-maelstro.fullname" . }}-maelstro-frontend
