{{- if and (.Values.maelstro_backend.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: maelstro-creds-ext-plateform-secret
  labels:
    {{- include "helm-maelstro.labels" . | nindent 4 }}
type: Opaque
data: |
{{- range .Values.credentials }}
{{ .name | indent 2 }}_USERNAME: {{ .username | b64enc }}
{{ .name | indent 2 }}_PASSWORD: {{ .password | b64enc }}
{{- end }}
{{- end }}