name: CI

on:
  push:

jobs:
  backend-check:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1

      - name: build
        run: docker compose build check

      - name: check
        run: docker compose run --rm check

      - name: test
        run: docker compose run --rm check pytest --cov=maelstro tests/

  frontend-check:
    runs-on: ubuntu-22.04
    name: Front Build and Tests
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install # --frozen-lockfile

      - name: Lint
        working-directory: ./frontend
        run: npm run lint

      - name: Unit tests
        working-directory: ./frontend
        run: npm run test:unit --coverage.enabled true

      # - name: Report Frontend Coverage
      #   # Set if: always() to also generate the report if tests are failing
      #   # Only works if you set `reportOnFailure: true` in your vite config as specified above
      #   if: always()
      #   uses: davelosert/vitest-coverage-report-action@v2
      #   with:
      #     working-directory: ./frontend

      - name: Build
        working-directory: ./frontend
        run: npm run build

  build:
    runs-on: ubuntu-22.04
    name: Build Docker images
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: docker compose build maelstro-back maelstro-front
